### PR TITLE
Remove libnvrtc dyn library dependency

### PR DESCRIPTION
**Pull request by jean-m-cyr**
- Stub functions will return error if libnvrtc.so can't be loaded
  but at least miner will load and live long enough to give diagnostics.
- Linux only implementation, though areas that are OS specific are
  clearly marked out with #ifdefs. Windows version should be nearly
  identical, but I don't have Windows to test on.

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
Ok, building under cicle/ci and Appveyor (linux & Windows). I have no idea how to get the travis build working for Apple!
Linux binary will load correctly in the absence of libnvrtc.so. Windows still depends on nvrtc...dll, needs update to nvstub.c for Windows.

**Comment by jean-m-cyr** [comment]
It might be a good idea, now that the dependency is removed, to remove the nvrtc*.dll copy to the Appveyor created distribution.
```
      cp C:\CUDA\v$env:CUDA_VER\bin\nvrtc*.dll bin\
      7z a build/ethminer.zip bin\nvrtc*.dll
```

**Comment by AndreaLanfranchi** [comment]
Wouldn't it then require users to install full cuda toolkit ?


Sent from mobile. Apologies for brevity and typos.
In data 16 febbraio 2019 21:38:44 Jean Cyr <notifications@github.com> ha 
scritto:

**Comment by jean-m-cyr** [comment]
True. I guess you're planning to release three separate versions then? One each for CUDA 8, 9 , and 10.

**Comment by AndreaLanfranchi** [comment]
I'd like to step further. Only one release for all three flavors. Better 
yet a single binary for any combination of CUDA/OpenCL


Sent from mobile. Apologies for brevity and typos.
In data 16 febbraio 2019 22:02:36 Jean Cyr <notifications@github.com> ha 
scritto:

**Comment by jean-m-cyr** [comment]
In both Linux and Windows the dynamically linked libraries need to match the installed driver version. Like we do for Linux, it might be safest to make it a user responsibility to install the required dynamic library.

**Comment by AndreaLanfranchi** [comment]
Superseded by #74 
Thank you anyway @jean-m-cyr

**Pull request closed without merging**
