### PR TITLE
Continuos integration

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
Test

### CODE REVIEW

**Comment by MariusVanDerWijden** [comment]
"CMake Error at /home/travis/build/AndreaLanfranchi/ethminer/build/ethminer/cmake_install.cmake:44 (file):
  file cannot create directory: /kernels.  Maybe need administrative
  privileges."

**Comment by AndreaLanfranchi** [comment]
@MariusVanDerWijden yes but strangely enough with CUDA on works. And CUDA has nothing to do with binary kernels.

**Comment by jean-m-cyr** [comment]
Looks like the jobs that are failing are the only ones trying to do actual install.

**Comment by AndreaLanfranchi** [comment]
Yep which actually we would not need. At the end is only an archive package to explode and to run in whichever location it is.

**Comment by AndreaLanfranchi** [comment]
Not relevant anymore.
Superseded by #74

**Pull request closed without merging**
